// NEXUS Design System — Cyberpunk Research Terminal
export const C = {
  bg:           '#04080f',
  surface:      '#080d18',
  card:         '#0c1220',
  border:       '#1a2540',
  borderBright: '#1e3a5f',
  cyan:         '#00d4ff',
  cyanDim:      '#0099bb',
  green:        '#00ff88',
  greenDim:     '#00bb66',
  red:          '#ff3355',
  redDim:       '#cc2244',
  orange:       '#ff8800',
  yellow:       '#ffd700',
  purple:       '#9966ff',
  purpleDim:    '#6644cc',
  text:         '#c8d8f0',
  textDim:      '#5a7a9a',
  textBright:   '#e8f4ff',
}

export const S = {
  card: {
    background: C.card,
    border: `1px solid ${C.border}`,
    borderRadius: '6px',
    padding: '20px',
  },
  cardHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '16px',
    paddingBottom: '12px',
    borderBottom: `1px solid ${C.border}`,
  },
  cardTitle: {
    fontSize: '11px',
    letterSpacing: '3px',
    color: C.cyan,
    fontWeight: '600',
  },
  label: {
    fontSize: '10px',
    letterSpacing: '2px',
    color: C.textDim,
    display: 'block',
    marginBottom: '6px',
    marginTop: '14px',
  },
  input: {
    width: '100%',
    background: '#060b14',
    border: `1px solid ${C.border}`,
    color: C.text,
    padding: '10px 14px',
    fontSize: '13px',
    borderRadius: '4px',
    transition: 'border-color 0.2s',
  },
  textarea: {
    width: '100%',
    background: '#060b14',
    border: `1px solid ${C.border}`,
    color: C.text,
    padding: '10px 14px',
    fontSize: '12px',
    borderRadius: '4px',
    resize: 'vertical',
    minHeight: '120px',
    lineHeight: '1.6',
  },
  select: {
    width: '100%',
    background: '#060b14',
    border: `1px solid ${C.border}`,
    color: C.text,
    padding: '9px 12px',
    fontSize: '12px',
    borderRadius: '4px',
    cursor: 'pointer',
  },
  terminal: {
    background: '#020508',
    border: `1px solid ${C.border}`,
    borderRadius: '4px',
    padding: '14px',
    fontSize: '12px',
    lineHeight: '1.8',
    minHeight: '200px',
    maxHeight: '380px',
    overflowY: 'auto',
    fontFamily: 'inherit',
  },
  tag: (color) => ({
    display: 'inline-block',
    fontSize: '9px',
    letterSpacing: '1px',
    color,
    border: `1px solid ${color}`,
    padding: '2px 7px',
    borderRadius: '2px',
    marginRight: '6px',
  }),
  btn: (color = C.cyan, disabled = false) => ({
    background: disabled ? C.border : 'transparent',
    color: disabled ? C.textDim : color,
    border: `1px solid ${disabled ? C.border : color}`,
    padding: '9px 20px',
    fontSize: '11px',
    letterSpacing: '2px',
    cursor: disabled ? 'not-allowed' : 'pointer',
    borderRadius: '4px',
    transition: 'all 0.2s',
    fontWeight: '600',
  }),
  metricCard: {
    background: '#080d18',
    border: `1px solid ${C.border}`,
    borderRadius: '4px',
    padding: '14px',
    textAlign: 'center',
  },
  grid2: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' },
  grid3: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '12px' },
  grid4: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '12px' },
  fullWidth: { gridColumn: '1 / -1' },
}

export const severityColor = (s) => {
  const map = { CRITICAL: C.red, HIGH: C.orange, MEDIUM: C.yellow, LOW: C.green, INFO: C.cyan }
  return map[s?.toUpperCase()] || C.textDim
}

export const ts = () => new Date().toISOString().slice(11, 19)
